# Copyright 2026 Canarias Conectada
# License AGPL-3.0 or later (https://www.gnu.org/licenses/agpl).

import json

from odoo import http
from odoo.http import request

# The service worker can only control the pages under its own path, so it has
# to be served from the root for the whole microsite to be in scope. That is
# why this route is /service-worker.js and not something under /website_pwa/.
SERVICE_WORKER_PATH = "/service-worker.js"

# Bumping this string invalidates every visitor's cached shell on their next
# visit. Change it whenever the offline page or the caching rules change.
CACHE_VERSION = "canarias-pwa-v1"

SERVICE_WORKER_TEMPLATE = """
// Generated by website_pwa. Do not edit in the browser.
const CACHE = "%(cache)s";
const OFFLINE_URL = "%(offline)s";

self.addEventListener("install", (event) => {
    // Pre-cache only the offline page. Caching the shell of a site whose
    // content is edited daily would serve visitors stale pages for a week.
    event.waitUntil(
        caches.open(CACHE).then((cache) => cache.add(OFFLINE_URL))
            .then(() => self.skipWaiting())
    );
});

self.addEventListener("activate", (event) => {
    event.waitUntil(
        caches.keys()
            .then((keys) => Promise.all(
                keys.filter((k) => k !== CACHE).map((k) => caches.delete(k))
            ))
            .then(() => self.clients.claim())
    );
});

self.addEventListener("fetch", (event) => {
    const request = event.request;
    // Network-first, and only for page navigations. Everything else (assets,
    // XHR, the backend) goes straight to the network: an e-commerce site
    // must never serve a cached price or a cached cart.
    if (request.mode !== "navigate") {
        return;
    }
    event.respondWith(
        fetch(request).catch(() => caches.match(OFFLINE_URL))
    );
});
""".strip()

OFFLINE_HTML = """
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1"/>
    <title>Sin conexión</title>
    <style>
        body {
            font-family: system-ui, -apple-system, sans-serif;
            display: flex; align-items: center; justify-content: center;
            min-height: 100vh; margin: 0; padding: 2rem;
            text-align: center; color: #333; background: %(background)s;
        }
        h1 { font-size: 1.4rem; margin-bottom: .5rem; }
        p { color: #666; max-width: 28rem; }
    </style>
</head>
<body>
    <div>
        <h1>Sin conexión</h1>
        <p>
            No hemos podido cargar la página. Comprueba tu conexión a
            internet y vuelve a intentarlo.
        </p>
    </div>
</body>
</html>
""".strip()


class WebsitePWA(http.Controller):
    """Public endpoints that make a microsite installable.

    All of them answer 404 when the website has ``pwa_enabled`` off, so
    disabling the app for one merchant really removes it: the browser stops
    finding a manifest and drops the install prompt.
    """

    @http.route(
        "/website_pwa/manifest.webmanifest",
        type="http",
        auth="public",
        website=True,
        sitemap=False,
    )
    def manifest(self, **kwargs):
        website = request.env["website"]._pwa_current()
        if not website:
            return request.not_found()
        return request.make_response(
            json.dumps(website._pwa_manifest_values()),
            headers=[
                ("Content-Type", "application/manifest+json"),
                ("Cache-Control", "public, max-age=300"),
            ],
        )

    @http.route(
        SERVICE_WORKER_PATH,
        type="http",
        auth="public",
        website=True,
        sitemap=False,
    )
    def service_worker(self, **kwargs):
        website = request.env["website"]._pwa_current()
        if not website:
            return request.not_found()
        return request.make_response(
            self._pwa_service_worker_content(website),
            headers=[
                ("Content-Type", "application/javascript"),
                # The worker itself must never be cached for long or a fix
                # cannot reach the phones that already installed the app.
                ("Cache-Control", "no-cache"),
                # Belt and braces: some proxies would otherwise narrow the
                # scope to the directory the file is served from.
                ("Service-Worker-Allowed", "/"),
            ],
        )

    def _pwa_service_worker_content(self, website):
        """Body of the service worker, as a single string.

        Split out of the route so extension modules can override it and
        append their own handlers, exactly the way ``mail`` extends the
        backend worker in ``mail/controllers/webmanifest.py``:

            def _pwa_service_worker_content(self, website):
                body = super()._pwa_service_worker_content(website)
                return body + MY_EXTRA_HANDLERS

        Anything appended here ships to phones that already installed the
        app, so keep the output byte-stable unless CACHE_VERSION moves too.
        """
        return SERVICE_WORKER_TEMPLATE % {
            "cache": f"{CACHE_VERSION}-{website.id}",
            "offline": "/website_pwa/offline",
        }

    @http.route(
        "/website_pwa/offline",
        type="http",
        auth="public",
        website=True,
        sitemap=False,
    )
    def offline(self, **kwargs):
        website = request.env["website"].get_current_website()
        return request.make_response(
            OFFLINE_HTML % {"background": website.pwa_background_color or "#ffffff"},
            headers=[("Content-Type", "text/html; charset=utf-8")],
        )

    @http.route(
        "/website_pwa/icon/<int:size>.png",
        type="http",
        auth="public",
        website=True,
        sitemap=False,
    )
    def icon(self, size, **kwargs):
        """Square PNG of the requested size.

        Serving through Odoo's generic image route was not enough: a manifest
        icon must really be a PNG of the declared size, and merchant logos are
        a mix of JPEG, transparent PNG and odd aspect ratios. This normalises
        them so the browser accepts the app as installable.
        """
        website = request.env["website"]._pwa_current()
        if not website or size not in (192, 512):
            return request.not_found()
        image = website._pwa_icon_png(size)
        if not image:
            return request.not_found()
        return request.make_response(
            image,
            headers=[
                ("Content-Type", "image/png"),
                ("Cache-Control", "public, max-age=3600"),
            ],
        )
